index:
    path: /
    controller: App\Controller\MainController::index

InternshipApply:
    path: /internship-apply
    controller: App\Controller\InternshipApplyController::index

Profile:
    path: /profile
    controller: App\Controller\ProfileController::index