index:
    path: /
    controller: App\Controller\MainController::index

InternshipApply:
    path: /internship-apply
    controller: App\Controller\InternshipApplyController::index

Profile:
    path: /app/profile
    controller: App\Controller\ProfileController::index

Admin:
    path: /admin
    controller: App\Controller\AdminController::index

Fixtures:
    path: /fixture
    controller: App\Controller\FixtureController::index